version: 2.1
orbs:
  hugo: circleci/hugo@1.3.0
  go: circleci/go@1.7.2

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - hugo/build:
          html-proofer: true
      - store_test_results:
          path: test_results

workflows:
  main:
    jobs:
      - build-and-test